config/routes.rb
Alarmknowledgebase::Application.routes.draw do
  devise_for :users

  match 'alarms/search' => 'alarms#search', :method => :get, :as => :search_alarm
  resources :alarms do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'robots/search' => 'robots#search', :method => :get, :as => :search_robot
  match 'robots/axes' => 'robots#axes', :method => :get, :as => :axes
  resources :robots do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'parts/search' => 'parts#search', :method => :get, :as => :search_part
  resources :parts
  resources :parts do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'diagnoses/search' => 'diagnoses#search', :method => :get, :as => :search_diagnosis
  match 'diagnoses/logfile' => 'diagnoses#logfile', :as => :diagnosis_logfile
  match 'diagnoses/analyze' => 'diagnoses#analyze', :as => :diagnosis_analyze
  match 'diagnoses/part' => 'diagnoses#part', :method => :get, :as => :diagnosis_part
  match 'diagnoses/manifests/get_replacement_by_part_name' => 'manifests#get_replacement_by_part_name'
  match 'diagnoses/robots/axes' => 'robots#axes'
  resources :diagnoses
  resources :diagnoses do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :search, :on => :collection
  end
  
  match '/uploads/diagnosis/diagnosing_diagram/:id/:filename' => 'gridfs#serve'
  match '/uploads/manifest/replacement_pdf/:id/:filename' => 'gridfs#serve'

  root :to => 'static_pages#home'

end

app/models/part.rb
class Part
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :part_no, :type => String
  field :name, :type => String
  #field :replacement_pdf, :type => String
  
  has_many :manifests, autosave: true, dependent: :delete#, {:group => :robot_id}
  accepts_nested_attributes_for :manifests, :allow_destroy => true
  
  validates_presence_of :part_no
  validates_uniqueness_of :part_no
  
  default_scope order_by(:created_at => :asc)
  
  key :part_no
  
  #mount_uploader :replacement_pdf, ReplacementPdfUploader
  
  # has_and_belongs_to_many :diagnoses
  #belongs_to :replacedpart
  
  def part_no_and_name
    "#{part_no}: #{name}"
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_filter :check_for_existing_part, :only => [:create]
  before_filter :authenticate_user!
  load_and_authorize_resource
 # caches_page :index
 
  def show
    #id = params[:id] # retrieve part ID from URI route
    #@part = Part.find(id) # look up part by unique ID
    # will render app/views/parts/show.<extension> by default
  end

  def index
    page = params[:page] || 1
    sort = params[:sort] || session[:sort]
    case sort
    when 'no'
      ordering,@no_header = :no, 'hilite'
    end
    
    @parts = Part.all.order_by([ordering, :asc]).page(page).per(10)
  end

  def new
    #@part = Part.new
    
    # default: render 'new' template
  end

  def create
    #@part = Part.create!(params[:part])
    if @part.save
      flash[:notice] = "Part '#{@part.part_no}' was successfully created."
      redirect_to parts_path
    else
      flash[:notice] = "Part '#{params[:part]}' was already existed."
      redirect_to parts_path
    end
  end

  def edit
    #@part = Part.find params[:id]
  end

  def update
    #@part = Part.find params[:id]
    @part.update_attributes!(params[:part])
    flash[:notice] = "Part '#{@part.part_no}' was successfully updated."
    redirect_to part_path(@part)
  end

  def destroy
    #@part = Part.find(params[:id])
    @part.destroy
    flash[:notice] = "Part '#{@part.part_no}' deleted."
    redirect_to parts_path
  end
  
  def search
    part_no = params[:part_no]
    if part_no
      @part = Part.where(:part_no => part_no).first
      respond_to do |format|
        format.js
      end
    end
  end
  
  def check_for_existing_part
    part = Part.where(:part_no => params[:part][:part_no]).first
    if part
      flash[:warning] = "Part '#{part.part_no}' already existed."
      redirect_to(part) and return
    end
  end
end

app/views/parts/_form.html.haml
= form_for @part, :multipart => true do |f|
  - if @part.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@part.errors.count, "error")
        prohibited this part from being saved:

      %ul#details
      - @part.errors.full_messages.each do |msg| 
        %li
          = msg

  %div.clear
    %div.left
      = f.label :part_no
    %div.left
      = f.text_field :part_no

  %div.clear
    %div.left
      = f.label :name
    %div.left
      = f.text_field :name

  %div.clear
    %div.left
      = f.label :manifests, 'Manifests'
    -#%div.left
    -#  = f.file_field :replacement_pdf
    -#- if @part.replacement_pdf && @part.replacement_pdf.path
    -#  %div.left
    -#    = f.check_box :remove_replacement_pdf
    -#    remove
    %table#alarms
      %thead
        %tr
          %th Robot
          %th Axis
          %th Replacement Instructions
          %th Remove record
      %tbody
        = f.fields_for :manifests do |builder|
          = render "manifest_fields", :f => builder

  %p
    = link_to_add_fields "Add Manifest", f, :manifests, {}, "#alarms"

  %br/
  %div.clear
    = f.submit

app/views/parts/_manifest_fields.html.haml
%tr.fields
  %td= f.collection_select :robot_id, Robot.all, :id, :code_and_model, {:include_blank => "Keep this selected if this part is irrelevant to robot"}, :style => "width:80%;"
  %td= f.select :axis, Robot.all_axes, :include_blank => "Keep this selected if this part is irrelevant to axis"
  %td= f.file_field :replacement_pdf
  %td= link_to_remove_fields "Remove", f

app/views/parts/_search_result.html.haml
%h2 Search Results

- if part.nil?
  %h2 No Part found
- else
  %table#alarms
    %thead
      %tr
        %th Part No.
        %th Name
        %th Replacement Instructions
      
    %tbody
      %tr
        %td= link_to "#{part.part_no}", part_path(part)
        %td= part.name
        - if part.manifests.length == 0
          %td
        - elsif part.manifests.length == 1 && part.manifests.first.robot_id.nil? && part.manifests.first.axis.empty?
          %td= link_to "#{File.basename(part.manifests.first.replacement_pdf.path)}", part.manifests.first.replacement_pdf_url
        - else
          %td= link_to "More Info", part_path(part)

app/views/parts/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Part

= render 'form'

app/views/parts/index.html.haml
-#  This file is app/views/parts/index.html.haml
%h1 All Parts

%table#alarms
  %thead
    %tr
      %th{:class => @no_header}= link_to 'Part No.', parts_path(:sort => 'no'), :id => 'no_header'
      %th Name
      %th Replacement Instructions
  %tbody
    - @parts.each do |part|
      %tr
        %td= link_to "#{part.part_no}", part_path(part)
        %td= part.name
        - if part.manifests.length == 0
          %td
        - elsif part.manifests.length == 1 && part.manifests.first.robot_id.nil? && part.manifests.first.axis.empty?
          %td= link_to "#{File.basename(part.manifests.first.replacement_pdf.path)}", part.manifests.first.replacement_pdf_url
        - else
          %td= link_to "More Info", part_path(part)

= paginate @parts

= link_to 'Add new part', new_part_path
%br/
%br/
= link_to 'Search part', search_part_path
%br/

-# = link_to 'Benchmark moviegoer.reviews', benchmark_path(:type=>'moviegoers')
-# <br/>
-# = link_to 'Benchmark movie.reviews', benchmark_path(:type=>'movies')

app/views/parts/new.html.haml
%h1 Create New Part

= render 'form'

app/views/parts/search.html.haml
%h1 Search Part

= form_tag search_part_path, :method => :get, :remote => true do
  %div.left
    = label :part_no, 'Part No.'
  %div.left
    = text_field_tag :part_no
  %div.left
    = submit_tag 'Search'

%div#search_result.clear

app/views/parts/search.js.haml
$('#search_result').html("#{escape_javascript(render :partial => "search_result", :locals => {:part => @part})}")

app/views/parts/show.html.haml
-# in app/views/parts/show.html.haml

%h1 Details about Part #{@part.part_no}

%ul#details
  %li
    Part No.:
    = @part.part_no
  %li
    Name:
    = @part.name
  %li
    Replacement Instructions (PDF):
    -#- if @part.replacement_pdf.file
    -#  = link_to "#{File.basename(@part.replacement_pdf.path)}", @part.replacement_pdf_url
    - if @part.manifests.size == 1 && @part.manifests.first.robot.nil?
      = link_to "#{File.basename(@part.manifests.first.replacement_pdf.path)}", @part.manifests.first.replacement_pdf_url
    - else
      %table#alarms
        %thead
          %tr
            %th Robot
            %th Axis
            %th Replacement Instructions
        %tbody
          - @part.manifests.each do |manifest|
            %tr
              - if user_signed_in? && (can? :show, manifest.robot)
                %td= link_to manifest.robot.model, robot_path(manifest.robot)
              - else
                %td= manifest.robot.model
              %td= manifest.axis
              %td= link_to "#{File.basename(manifest.replacement_pdf.path)}", manifest.replacement_pdf_url

-#= link_to 'Find conditions with this alarm', alarms_condition_path(@alarm)
<br/>
-#= link_to 'Malfunctioning parts to this alarm', replaced_parts_viewed_with_path(@alarm)
- if user_signed_in? && (can? :update, @part)
  <br/>
  = link_to 'Edit', edit_part_path(@part)
<br/>
- if user_signed_in? && (can? :destroy, @part)
  <br/>
  = button_to 'Delete', part_path(@part), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to part list', parts_path