config/routes.rb
Alarmknowledgebase::Application.routes.draw do
  devise_for :users

  match 'alarms/search' => 'alarms#search', :method => :get, :as => :search_alarm
  resources :alarms do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'robots/search' => 'robots#search', :method => :get, :as => :search_robot
  match 'robots/axes' => 'robots#axes', :method => :get, :as => :axes
  resources :robots do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'parts/search' => 'parts#search', :method => :get, :as => :search_part
  resources :parts
  resources :parts do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'diagnoses/search' => 'diagnoses#search', :method => :get, :as => :search_diagnosis
  match 'diagnoses/logfile' => 'diagnoses#logfile', :as => :diagnosis_logfile
  match 'diagnoses/analyze' => 'diagnoses#analyze', :as => :diagnosis_analyze
  match 'diagnoses/part' => 'diagnoses#part', :method => :get, :as => :diagnosis_part
  match 'diagnoses/manifests/get_replacement_by_part_name' => 'manifests#get_replacement_by_part_name'
  match 'diagnoses/robots/axes' => 'robots#axes'
  resources :diagnoses
  resources :diagnoses do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :search, :on => :collection
  end
  
  match '/uploads/diagnosis/diagnosing_diagram/:id/:filename' => 'gridfs#serve'
  match '/uploads/manifest/replacement_pdf/:id/:filename' => 'gridfs#serve'

  root :to => 'static_pages#home'

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
 before_filter :check_for_existing_diagnosis, :only => [:create]
 before_filter :authenticate_user!
 authorize_resource
 
 rescue_from CanCan::AccessDenied do |exception|
   redirect_to diagnosis_logfile_path
 end
 
 # caches_page :index
 
  def show
    @diagnosis = Diagnosis.find(params[:id]) # look up diagnosis by unique ID
    @alarms = @diagnosis.alarms.map { |code| Alarm.where(:code => code).first }
    #@solutions = @diagnosis.solutions.map { |solution| Part.where(:part_no => solution.part_no).first }
    @solutions_aggregated = {}
    all_times = zero_times = 0
    @diagnosis.solutions.each do |s|
      name = Part.where(:part_no => s.part_no).first.name
      if @solutions_aggregated[name]
        @solutions_aggregated[name] += s.times
      else
        @solutions_aggregated[name] = s.times
      end
      if s.times != 0
        all_times += s.times
      end
    end
    zero_times = @solutions_aggregated.select {|k, v| v == 0}.size + 1  # + 1 for the other
    @solutions_aggregated.each do |k, v|
      if v == 0
        @solutions_aggregated[k] = '1%'
      else
        percentage = (v * 1.0 / all_times) * (1 - zero_times * 1.0 / 100) * 100
        @solutions_aggregated[k] = "#{percentage.round(2)}%"
      end
    end
    # will render app/views/diagnoses/show.<extension> by default
  end

  def index
    per_page = 10
    page = params[:page] || 1
    @diagnoses = Diagnosis.all.page(page).per(per_page)
    @no = (page.to_i - 1) * per_page
  end

  def new
    # default: render 'new' template
    alarms = params[:alarms]
    @diagnosis = Diagnosis.new(:alarms => alarms)
    @diagnosis.solutions.build
  end

  def create
    @diagnosis = Diagnosis.new(params[:diagnosis])
    if @diagnosis.save
      flash[:notice] = "Successfully created diagnosis."
      redirect_to diagnosis_path(@diagnosis)
    else
      render :action => 'new'
    end
  end

  def edit
    @diagnosis = Diagnosis.find params[:id]
    @alarms = @diagnosis.alarms.map { |code| Alarm.where(:code => code).first }
  end

  def update
    @diagnosis = Diagnosis.find params[:id]
    @diagnosis.update_attributes!(params[:diagnosis])
    flash[:notice] = "Diagnosis '#{@diagnosis.id}' was successfully updated."
    redirect_to diagnosis_path(@diagnosis)
  end

  def destroy
    @diagnosis = Diagnosis.find params[:id]
    @diagnosis.destroy
    flash[:notice] = "Diagnosis '#{@diagnosis.id}' deleted."
    redirect_to diagnoses_path
  end

  def search
    alarms = params[:alarms]
    if alarms
      @diagnoses = Diagnosis.all_in(:alarms => alarms).select{ |d| (alarms & d.alarms) == alarms }
      
      per_page = 10
      page = params[:page] || 1
      @no = (page.to_i - 1) * per_page
      
      Kaminari.paginate_array(@diagnoses).page(page).per(per_page)
      respond_to do |format|
        format.js
      end
    end
  end
  
  def logfile
  end
  
  def analyze
    #if params[:date] and params[:time] and params[:range] and params[:log]
      respond_to do |format|
        #format.html
        format.js do
          # parse the params
          str_date = Date.parse(params[:date]).strftime('%d-%^b-%y')
          date_time = DateTime.strptime(params[:date] + " " + params[:time], '%Y-%m-%d %H:%M:%S')
          range = params[:range]
          contents = File.read(params[:log].tempfile)

          @solution_results = []
          @no_solution_results = []
          @alarms_happened_time = {} # to record each alarm_codes and their happened time
          #idx = contents.index str_date
          #if idx
          #  contents = contents[idx, contents.size - idx - 1]

            time_diff = case 
                          when range == "1" then 5
                          when range == "2" then 10
                          when range == "3" then 15
                          else 0
                        end * 60
            regex = /(?<datetime>[A-Za-z0-9\-\s\:]+)(\s)(\d+)(\.)(?<code>\d+)(\-)(?<severity>\d+)(\s\:\s)(?<message>.+)/
            prev_date = nil
            prev_str_date = ""
            messages = ""
            alarm_codes = []
            contents.each_line do |l|
              next if (regex =~ l).nil?
              data = Regexp.last_match
              str_dt = data[:datetime]
              dt = DateTime.parse(str_dt)
              severity = data[:severity]

              next if dt - date_time < 0 # skip all alarms before the specified time

              if time_diff != 0 and (((dt - date_time) * 1.days).to_i > time_diff) # stop iterating when error happened after the time range
                size = alarm_codes.size
                if size > 0
                  if @alarms_happened_time[alarm_codes]
                    @alarms_happened_time[alarm_codes] << prev_str_date
                  else
                    @alarms_happened_time[alarm_codes] = [prev_str_date]
                    #diagnosis = Diagnosis.where(:alarms.sort => alarm_codes.sort).first # Find the corresponding parts replaced in the DB
                    diagnosis = Diagnosis.where(:alarms => alarm_codes).first # Find the corresponding parts replaced in the DB
                    if diagnosis
                      @solution_results = @solution_results << [alarm_codes, messages, diagnosis]
                    else
                      @no_solution_results = @no_solution_results << [alarm_codes, messages, diagnosis]
                    end
                  end
                end
                break
              end

              next if severity == "00" or severity == "01" or severity == "02" # skip all infos and warnings

              code, message = data[:code], CGI::escapeHTML(data[:message])

              if prev_date != dt
                if !prev_date.nil?
                  size = alarm_codes.size
                  if size > 0
                    if @alarms_happened_time[alarm_codes]
                      @alarms_happened_time[alarm_codes] << prev_str_date
                    else
                      @alarms_happened_time[alarm_codes] = [prev_str_date]
                      #diagnosis = Diagnosis.where(:alarms.sort => alarm_codes.sort).first # Find the corresponding parts replaced in the DB
                      diagnosis = Diagnosis.where(:alarms => alarm_codes).first # Find the corresponding parts replaced in the DB
                      if diagnosis
                        @solution_results = @solution_results << [alarm_codes, messages, diagnosis]
                      else
                        @no_solution_results = @no_solution_results << [alarm_codes, messages, diagnosis]
                      end
                    end
                  end
                end
                prev_date, prev_str_date, alarm_codes, messages = dt, str_dt, [code], "#{code} #{message}"
              else
                alarm_codes = alarm_codes << code
                messages = messages + "<br>" + "#{code} #{message}"
              end
            end
          #end
          
          if !current_user.admin?
            error_log = ErrorLog.new
            error_log.delay.persist_and_send_mail(current_user.id, params[:date], params[:time], params[:range], contents, params[:log].original_filename)
          end
        end
      end
    #end
  end
  
  def part
    @part_name = params[:part]
  end
  
  def check_for_existing_diagnosis
    diagnosis = Diagnosis.where(:alarms => params[:diagnosis][:alarms]).first
    if diagnosis
      flash[:warning] = "Diagnosis '#{diagnosis.alarms}' already existed."
      redirect_to(diagnosis) and return
    end
  end
  
  def self.parse_error_log(str_date, date_time, range, log_file)
    
  end
  
end

app/views/diagnoses/_alarm_fields.html.haml
%div.fields
  %div.clear
    - if f
      %div.left
        = f.label :code, "Code"
      %div.left
        -#= f.collection_select :alarms, Alarm.all.order_by([:code, :asc]), :code, :code, {}, :name => "diagnosis[alarms][]", :cache => true
        -#= f.text_field :alarms, :id => "text_#{id}", :name => "diagnosis[alarms][]", "data-remote" => true, "data-url" => "/alarms/show", "data-type" => "json"
        = f.text_field :alarms, :id => "text_#{id}", :name => "diagnosis[alarms][]", :value => alarm
    - else
      %div.left
        = label :code, "Code"
      %div.left
        = text_field_tag "alarms[]", nil, :id => "text_#{id}"
    
    %div.left
      = link_to_remove_fields "remove"
    %div.left
      %div{:id => "hidden_#{id}"}

:javascript
  $("#text_#{id}").on('keyup', function(){
    $.ajax({
      success: function(alarm) {
        if (alarm) {
          $("#hidden_#{id}").html(alarm.message);
        } else {
          $("#hidden_#{id}").html("No corresponding alarm");
        }
      },
      data: 'code=' + $("#text_#{id}").val(),
      dataType: 'json',
      type: 'get',
      url: '/alarms/search/'
    })
  });

  $("#text_#{id}").on('ajax:beforeSend', function(evt){
    
  });

  $("#text_#{id}").on('ajax:success', function(evt, alarm) {
    // data is now an array containing your objects 
    // you can dump them on firebug or your web browser console using console.log(data); 
    if (alarm) {
      $("#hidden_#{id}").html(HTMLEncode(alarm.message));
    } else {
      $("#hidden_#{id}").html("No corresponding alarm");
    }
  });

app/views/diagnoses/_alarm_fields_without_parent.html.haml
%div.fields
  %div.clear
    %div.left
      = label :code, "Code"
    %div.left
      = collection_select :alarm, :code, Alarm.all.order_by([:code, :asc]), :code, :code, {}, :name => "alarms[]"
    %div.left
      = link_to_remove_fields "remove"
    %div.left
      %div#alarm_message

app/views/diagnoses/_diagnose_result.html.haml
%h2 Diagnose Results

- if @solution_results.empty? and @no_solution_results.empty?
  %h2 No Matched Errors found
- else
  -# results = Kaminari.paginate_array(results).page(1).per(10)
  %table#alarms
    %thead
      %tr
        %th Date Time
        %th Error Messages
        %th Diagnoses
        %th Detail
      
    %tbody
      - if @solution_results.empty? && !current_user.admin?
        %h2 Sorry, there is no knowledge to your problems but your error log is sent to the administrator.
      - @solution_results.each do |result|
        %tr
          %td= @alarms_happened_time[result[0]].join("<br>")
          %td= result[1]
          -#- if result[2].nil?
          -#  %td= "No Solutions"
          -#  %td= link_to "Create", new_diagnosis_path
          -#- else
          %td= result[2].solutions.map{|s| "#{Part.where(:part_no => s.part_no).first.name} [#{s.times}]"}.join("<br>")
          %td= link_to "More Info", diagnosis_path(result[2])
      - if current_user.admin?
        - @no_solution_results.each do |result|
          %tr
            %td= @alarms_happened_time[result[0]].join("<br>")
            %td= result[1]
            %td= "No Knowledge"
            - if user_signed_in? && (can? :create, Diagnosis)
              %td= link_to "Create", new_diagnosis_path(:alarms => result[0])
            - else
              %td

  -#= paginate results

app/views/diagnoses/_search_result.html.haml
%h2 Search Results

- if diagnoses.nil? || diagnoses.empty?
  %h2 No Diagnosis found
- else
  %table#alarms
    %thead
      %tr
        %th No
        %th Alarm Codes
        %th Solutions
        %th Detail
      
    %tbody
      - diagnoses.each do |diagnosis|
        %tr
          %td= @no += 1
          %td= diagnosis.alarms.join("<br>").html_safe
          %td= diagnosis.solutions.map { |s| "#{Part.where(:part_no => s.part_no).first.name} [#{s.times}]" }.join("<br>").html_safe
          %td= link_to "More Info", diagnosis_path(diagnosis)

app/views/diagnoses/_solution_fields.html.haml
%div.fields
  %div.clear
    %div.left
      = f.label :part_no, "Part No."
    %div.left
      = f.collection_select :part_no, Part.all, :part_no, :part_no_and_name, {}, :style => "width:100%;"
    - if opt[:new]
      %div{:style => "display: none"}
        = f.label :times, "Times"
      %div{:style => "display: none"}
        = f.text_field :times, :value => 0
      %div.left
        = check_box_tag :replaced, "0", false, :onchange => "check_part_replaced(this)"
      %div.left
        = label "", "Replaced"
    - else
      %div.left
        = f.label :times, "Times"
      %div.left
        = f.text_field :times
    %div.left
      = link_to_remove_fields "remove", f

  %div.clear
    %div.left
      = f.label :description, "Description"
    %div.left
      = f.text_area :description, :size => "40x10"
    %div.left
      = f.label :example, "Example"
    %div.left
      = f.text_area :example, :size => "40x10"

app/views/diagnoses/analyze.js.haml
= remotipart_response do
  $('#diagnose_result').html("#{escape_javascript(render :partial => "diagnose_result")}")

app/views/diagnoses/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Diagnosis

%h3 Alarms Happened
%table#alarms
  %thead
    %tr
      %th Code
      %th Error Message
      %th Severity
  %tbody
    - @alarms.each do |alarm|
      %tr
        %td= alarm.code
        %td= alarm.message
        %td= alarm.severity

= form_for @diagnosis do |f|
  %h2 Diagnosing Diagram
  %div#diagram
    %div.clear
      %div.left
        = f.label :diagnosing_diagram, "Diagram"
      %div.left
        = f.file_field :diagnosing_diagram
      %div.left
        = f.check_box :remove_diagnosing_diagram
      remove
    %div.clear

  %h2 Solutions
  %div#solutions
    = f.fields_for :solutions do |s|
      = render "solution_fields", :f => s, :opt => {}
  %div.clear
    = link_to_add_fields "Add Solution", f, :solutions, :new => true

  %br/
  %div.clear
    = submit_tag 'Update Diagnosis Info'

app/views/diagnoses/index.html.haml
-#  This file is app/views/diagnoses/index.html.haml
%h1 All Diagnoses

%table#alarms
  %thead
    %tr
      %th No
      %th Alarm Codes
      %th Solutions
      %th Detail
      
  %tbody
    - @diagnoses.each do |diagnosis|
      %tr
        %td= @no += 1
        %td= diagnosis.alarms.join("<br>").html_safe
        %td= diagnosis.solutions.map{ |s| "#{Part.where(:part_no => s.part_no).first.name} [#{s.times}]" }.join("<br>").html_safe
        %td= link_to "More Info", diagnosis_path(diagnosis)

= paginate @diagnoses

= link_to 'Add new diagnosis', new_diagnosis_path
%br/
%br/
= link_to 'Search diagnosis', search_diagnosis_path
%br/
%br/
= link_to 'Diagnose error log', diagnosis_logfile_path
-# <br/>
-# = link_to 'Benchmark movie.reviews', benchmark_path(:type=>'movies')

app/views/diagnoses/logfile.html.haml
%h1 Diagnose Logfile

= form_tag diagnosis_analyze_path, :multipart => true, :remote => true do
  %div.clear
    %div.left
      = label :date, "Date:"
    %div#datetimepicker4.input-append.left
      = text_field_tag :date, nil, "data-format" => "yyyy-MM-dd"
      %span.add-on
        %i{:class => "icon-calendar", "data-time-icon" => "icon-time", "data-date-icon" => "icon-calendar"}

  %br/

  %div.clear
    %div.left
      = label :time, "Time:"
    %div#datetimepicker3.input-append.left
      = text_field_tag :time, nil, "data-format" => "hh:mm:ss"
      %span.add-on
        %i{:class => "icon-time", "data-time-icon" => "icon-time", "data-date-icon" => "icon-calendar"}

  %div.clear
    %div.left
      = label :range, "Time range:"
    %div.left
      = collection_select nil, nil, [[1, "5 min"], [2, "10 min"], [3, "15 min"], [4, "All"]], :first, :second, {}, {:name => "range"}

  %div.clear
    %div.left
      = label :log, "Error Log:"
    %div.left
      = file_field_tag :log, :accept => 'text/log'

  %br/
  %br/
  %div.clear
    = submit_tag 'Analyse'

%div#diagnose_result.clear

:javascript
  $(function() {
    $('#datetimepicker3').datetimepicker({
      pickDate: false
    });
    $('#datetimepicker4').datetimepicker({
      pickTime: false
    });
  });

app/views/diagnoses/new.html.haml
%h1 Create New Diagnosis

= form_for @diagnosis do |f|
  %h2 Alarm Info
  -#%div#alarms
    -#= render :partial => "alarm_fields", :locals => {:f => f, :id => Time.now.to_f}
  - if @diagnosis.alarms
    - @diagnosis.alarms.each do |alarm|
      = render :partial => "alarm_fields", :locals => {:f => f, :id => Time.now.to_f, :alarm => alarm}
  - else
    = render :partial => "alarm_fields", :locals => {:f => f, :id => Time.now.to_f, :alarm => ""}
  %div.clear
    = link_to_add_alarms "Add Alarm", f, :alarms

  %h2 Diagnosing Diagram
  %div#diagram
    %div.clear
      %div.left
        = f.label :diagnosing_diagram, "Diagram"
      %div.left
        = f.file_field :diagnosing_diagram
    %div.clear
	
  %h2 Solutions
  %div#solutions
    -# @diagnosis.solutions.each do |solution|
    = f.fields_for :solutions do |s|
      = render "solution_fields", :f => s, :opt => {:new => true}
  %div.clear
    = link_to_add_fields "Add Solution", f, :solutions, :new => true

  %br/
  %br/
  %div.clear
    = f.submit "Save Changes"

app/views/diagnoses/part.html.haml
-# in app/views/parts/show.html.haml

%h1 Details about Part #{@part_name}

%ul#details
  %li
    Name:
    = @part_name
  %li
    Replacement Instructions (PDF):
    %table#alarms
      %thead
        %tr
          %th Robot
          %th Axis
          %th Replacement Instructions
      %tbody
        %tr
          %td= collection_select nil, :robot_id, Robot.all, :id, :code_and_model, {}, { :id => "robot_id", :onchange => "update_replacement_field()" }
          %td= select nil, :axis, Robot.all_axes, { :include_blank => "Keep this selected if this part is irrelevant to axis" }, { :id => "axis", :onchange => "update_replacement_field()" }
          %td#replacement_field

:javascript
  function update_replacement_field() {
    $.ajax({
      url: "manifests/get_replacement_by_part_name",
      type: "GET",
      data: {"part_name" : '#{@part_name}', "robot_id" : $("#robot_id").val(), "axis" : $("#axis").val()},
      dataType: "html",
      success: function(data) {
        $("#replacement_field").html(data);
      }
    });
  }

  function update_axis_field() {

  }

  $(document).ready(function() {
    update_replacement_field();
  })

app/views/diagnoses/search.html.haml
%h1 Search Diagnosis

= form_tag search_diagnosis_path, :method => :get, :remote => true do
  -#%div#alarms
    -#= render "alarm_fields_without_parent"
  = render :partial => "alarm_fields", :locals => {:f => nil, :id => Time.now.to_f}
  %div.clear
    -#= link_to_add_alarms_without_parent "Add Alarm"
    = link_to_add_alarms "Add Alarm", nil, :alarms

  %br/
  %br/
  %div.clear
    = submit_tag 'Search'

%div#search_result.clear

app/views/diagnoses/search.js.haml
$('#search_result').html("#{escape_javascript(render :partial => "search_result", :locals => {:diagnoses => @diagnoses})}")

app/views/diagnoses/show.html.haml
-# in app/views/diagnoses/show.html.haml

%h1 Details about Diagnosis

%h3 Alarms Happened
%table#alarms
  %thead
    %tr
      %th Code
      %th Error Message
      %th Severity
  %tbody
    - @alarms.each do |alarm|
      %tr
        %td= alarm.code
        %td= alarm.message
        %td= alarm.severity

- if !@diagnosis.diagnosing_diagram_url.nil?
  %h3 Diagnosing Diagram
  = image_tag @diagnosis.diagnosing_diagram_url
  <br/>

%h3 Solutions
%table#alarms
  %thead
    %tr
      -#%th Part No
      %th Part Name
      %th Field Data Percentage
      %th Description
      %th Example
      %th Fixing Instructions
  %tbody
    -#- @diagnosis.solutions.each do |solution|
    - @solutions_aggregated.each_pair do |key, value|
      %tr
        -#%td= solution.part_no
        %td= key
        %td= value
        %td= @diagnosis.solutions.detect {|s| Part.where(:part_no => s.part_no).first.name == key }.description
        %td= @diagnosis.solutions.detect {|s| Part.where(:part_no => s.part_no).first.name == key }.example
        - part = Part.where(:name => key).first
        - if part.manifests.length == 0
          %td
        - elsif part.manifests.length == 1 && part.manifests.first.robot_id.nil? && part.manifests.first.axis.empty?
          %td= link_to "#{File.basename(part.manifests.first.replacement_pdf.path)}", part.manifests.first.replacement_pdf_url
        - else
          %td= link_to "More Info", diagnosis_part_path(:part => part.name)
    %tr
      %td Other
      %td 1%
      %td
      %td
      %td

-#= link_to 'Find conditions with this alarm', alarms_condition_path(@alarm)
<br/>
-#= link_to 'Malfunctioning parts to this alarm', replaced_parts_viewed_with_path(@alarm)
- if user_signed_in? && (can? :update, @diagnosis)
  <br/>
  = link_to 'Edit', edit_diagnosis_path(@diagnosis)
<br/>
- if user_signed_in? && (can? :destroy, @diagnosis)
  <br/>
  = button_to 'Delete', diagnosis_path(@diagnosis), :method => :delete, :confirm => 'Are you sure?'
- if user_signed_in? && (can? :index, @diagnosis)
  = link_to 'Back to diagnosis list', diagnoses_path