config/routes.rb
Alarmknowledgebase::Application.routes.draw do
  devise_for :users

  match 'alarms/search' => 'alarms#search', :method => :get, :as => :search_alarm
  resources :alarms do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'robots/search' => 'robots#search', :method => :get, :as => :search_robot
  match 'robots/axes' => 'robots#axes', :method => :get, :as => :axes
  resources :robots do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'parts/search' => 'parts#search', :method => :get, :as => :search_part
  resources :parts
  resources :parts do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'diagnoses/search' => 'diagnoses#search', :method => :get, :as => :search_diagnosis
  match 'diagnoses/logfile' => 'diagnoses#logfile', :as => :diagnosis_logfile
  match 'diagnoses/analyze' => 'diagnoses#analyze', :as => :diagnosis_analyze
  match 'diagnoses/part' => 'diagnoses#part', :method => :get, :as => :diagnosis_part
  match 'diagnoses/manifests/get_replacement_by_part_name' => 'manifests#get_replacement_by_part_name'
  match 'diagnoses/robots/axes' => 'robots#axes'
  resources :diagnoses
  resources :diagnoses do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :search, :on => :collection
  end
  
  match '/uploads/diagnosis/diagnosing_diagram/:id/:filename' => 'gridfs#serve'
  match '/uploads/manifest/replacement_pdf/:id/:filename' => 'gridfs#serve'

  root :to => 'static_pages#home'

end

app/models/robot.rb
class Robot
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :code, :type => String
  field :model, :model => String
  field :axes, :type => Hash
  
  has_many :manifests, autosave: true, dependent: :delete
  accepts_nested_attributes_for :manifests, :allow_destroy => true
  
  validates_presence_of :code
  validates_uniqueness_of :code
  
  default_scope order_by(:created_at => :asc)
  key :code
  
  def self.all_axes
    %w(1 2 3 4 5 6)
  end
  
  def code_and_model
    "#{code}: #{model}"
  end
  
  def axes_abbr
    if axes
      Robot.all_axes.map do |key|
        if (axes[key] == "1")
          key
        else
          "-"
        end
      end.join
    end
  end
  
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_filter :check_for_existing_robot, :only => [:create]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /robots
  # GET /robots.json
  def index
    page = params[:page] || 1
    sort = params[:sort] || session[:sort]
    case sort
    when 'no'
      ordering,@no_header = :no, 'hilite'
    end
    
    @robots = Robot.all.order_by([ordering, :asc]).page(page).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @robots }
    end
  end

  # GET /robots/1
  # GET /robots/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @robot }
    end
  end

  # GET /robots/new
  # GET /robots/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @robot }
    end
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render json: @robot, status: :created, location: @robot }
      else
        format.html { render action: "new" }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /robots/1
  # PUT /robots/1.json
  def update

    respond_to do |format|
      if @robot.update_attributes(params[:robot])
        format.html { redirect_to @robot, notice: 'Robot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy

    respond_to do |format|
      format.html { redirect_to robots_url }
      format.json { head :ok }
    end
  end
  
  def search
    code = params[:code]
    if code
      @robot = Robot.where(:code => code).first
      respond_to do |format|
        format.js
      end
    end
  end
  
  def axes
    respond_to do |format|
      format.json { render json: @robot.axes.keys }
    end
  end
  
  def check_for_existing_robot
    robot = Robot.where(:code => params[:robot][:code]).first
    if robot
      flash[:warning] = "Robot '#{robot.code}' already existed."
      redirect_to(robot) and return
    end
  end
end

app/views/robots/_form.html.haml
= form_for(@robot) do |f|
  - if @robot.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@robot.errors.count, "error")
        prohibited this robot from being saved:

      %ul#details
      - @robot.errors.full_messages.each do |msg| 
        %li
          = msg

  %div.clear
    %div.left
      = f.label :code
    %div.left
      = f.text_field :code

  %div.clear
    %div.left
      = f.label :model
    %div.left
      = f.text_field :model

  %div.clear
    %div.left
      = f.label :axes
    %div.left
      - Robot.all_axes.each do |n|
        = "Axis #{n}"
        -#= f.check_box :axes, {:name => "robot[axes][#{n}]"}, (@robot.axes && @robot.axes[n] == "1")
        = check_box_tag "robot[axes][#{n}]", 1, (@robot.axes && @robot.axes[n] == "1"), :id => "robots_axes_#{n}"
        <br/>

  %div.clear
    %div.left
      = f.label :manifests, 'Manifests'
    %table#alarms
      %thead
        %tr
          %th Axis
          %th Part
          %th Replacement Instructions
          %th Remove record
      %tbody
        = f.fields_for :manifests do |builder|
          = render "manifest_fields", :f => builder

  %p
    = link_to_add_fields "Add Manifest", f, :manifests, {}, "#alarms"

  %br/
  %div.clear
    = f.submit

app/views/robots/_manifest_fields.html.haml
%tr.fields
  %td= f.select :axis, Robot.all_axes, :include_blank => "Keep this selected if this part is irrelevant to axis"
  %td= f.collection_select :part_id, Part.all, :id, :part_no_and_name, :style => "width:80%;"
  %td= f.file_field :replacement_pdf
  %td= link_to_remove_fields "Remove", f

app/views/robots/_search_result.html.haml
%h2 Search Results

- if robot.nil?
  %h2 No Robot found
- else
  %table#alarms
    %thead
      %tr
        %th Code
        %th Model
        %th Axes
        %th Manifests
      
    %tbody
      %tr
        %td= link_to "#{robot.code}", robot_path(robot)
        %td= robot.model
        %td= robot.axes_abbr
        - if robot.manifests.size > 0
          %td= link_to "More Info", robot_path(robot)
        - else
          %td

app/views/robots/edit.html.haml
%h1 Edit Existing Robot

= render 'form'

app/views/robots/index.html.haml
-#  This file is app/views/robots/index.html.haml
%h1 All Robots

%table#alarms
  %thead
    %tr
      %th{:class => @no_header}= link_to 'Code', robots_path(:sort => 'no'), :id => 'no_header'
      %th Model
      %th Axes
      %th Manifests
  %tbody
    - @robots.each do |robot|
      %tr
        %td= link_to "#{robot.code}", robot_path(robot)
        %td= robot.model
        %td= robot.axes_abbr
        - if robot.manifests.size > 0
          %td= link_to "More Info", robot_path(robot)
        - else
          %td
    
= paginate @robots

= link_to 'Add new robot', new_robot_path
%br/
%br/
= link_to 'Search robot', search_robot_path
%br/

app/views/robots/new.html.haml
%h1 Create New Robot

= render 'form'

app/views/robots/search.html.haml
%h1 Search Robot

= form_tag search_robot_path, :method => :get, :remote => true do
  %div.left
    = label :code, 'Code'
  %div.left
    = text_field_tag :code
  %div.left
    = submit_tag 'Search'

%div#search_result.clear

app/views/robots/search.js.haml
$('#search_result').html("#{escape_javascript(render :partial => "search_result", :locals => {:robot => @robot})}")

app/views/robots/show.html.haml
-# in app/views/robots/show.html.haml

%h1 Details about Robot #{@robot.code}

%ul#details
  %li
    Code:
    = @robot.code
  %li
    Model:
    = @robot.model
  %li
    Axes:
    = @robot.axes_abbr
  %li
    Manifests:
    %table#alarms
      %thead
        %tr
          %th Axis
          %th Part
          %th Replacement Instructions
      %tbody
        - @robot.manifests.each do |manifest|
          %tr
            %td= manifest.axis
            %td= link_to manifest.part.name, part_path(manifest.part)
            %td= link_to "#{File.basename(manifest.replacement_pdf.path)}", manifest.replacement_pdf_url

<br/>
= link_to 'Edit', edit_robot_path(@robot)
<br/>
<br/>
= button_to 'Delete', robot_path(@robot), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to robot list', robots_path