config/routes.rb
Alarmknowledgebase::Application.routes.draw do
  devise_for :users

  match 'alarms/search' => 'alarms#search', :method => :get, :as => :search_alarm
  resources :alarms do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'robots/search' => 'robots#search', :method => :get, :as => :search_robot
  match 'robots/axes' => 'robots#axes', :method => :get, :as => :axes
  resources :robots do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'parts/search' => 'parts#search', :method => :get, :as => :search_part
  resources :parts
  resources :parts do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  match 'diagnoses/search' => 'diagnoses#search', :method => :get, :as => :search_diagnosis
  match 'diagnoses/logfile' => 'diagnoses#logfile', :as => :diagnosis_logfile
  match 'diagnoses/analyze' => 'diagnoses#analyze', :as => :diagnosis_analyze
  match 'diagnoses/part' => 'diagnoses#part', :method => :get, :as => :diagnosis_part
  match 'diagnoses/manifests/get_replacement_by_part_name' => 'manifests#get_replacement_by_part_name'
  match 'diagnoses/robots/axes' => 'robots#axes'
  resources :diagnoses
  resources :diagnoses do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :search, :on => :collection
  end
  
  match '/uploads/diagnosis/diagnosing_diagram/:id/:filename' => 'gridfs#serve'
  match '/uploads/manifest/replacement_pdf/:id/:filename' => 'gridfs#serve'

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "#"}Alarm KB
    -#by Kang Jiang

  %nav
    %ul
      %li= link_to "About", '#'
      %li= mail_to 'kang.jiang@comau.com', "Contact", :subject => "[Alarm KB] put your subject here"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  %div.navbar-inner
    %div.container
      = link_to "Alarm KB", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Alarms", alarms_path
          - if user_signed_in? && (can? :read, Part)
            %li= link_to "Parts", parts_path
          - if user_signed_in? && (can? :read, Robot)
            %li= link_to "Robots", robots_path
          - if user_signed_in? && ((can? :read, Diagnosis) || (can? :logfile, Diagnosis))
            %li= link_to "Diagnoses", diagnoses_path
          - if user_signed_in?
            %li#fat-menu.dropdown
              = link_to "#{current_user.email}<b class='caret'></b>".html_safe, "#", "class" => "dropdown-toggle", "data-toggle" => "dropdown"
              %ul.dropdown-menu
                %li= link_to "Profile", edit_user_registration_path(current_user)
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
          - else
            %li= link_to "Sign in", new_user_session_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

app/views/layouts/application.html.haml
%html
  %head
    %title Alarm Knowledge Base
    = stylesheet_link_tag 'application', :media => "all"
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/shim'

  %body
    = render 'layouts/header'
    
    %div.container
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - elsif flash[:alert]
        #alert.message= flash[:alert]

      = yield
      = render 'layouts/footer'

    -#%h1.title Alarm Knowledge Base
    -##main
    -#  - if flash[:notice]
    -#    #notice.message= flash[:notice]
    -#  - elsif flash[:warning]
    -#    #warning.message= flash[:warning]

    -#  = yield